services:
  mongo:
    image: mongo:6
    container_name: wanderlust_mongo
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: wanderlust_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    container_name: wanderlust_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
